language: java
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
    - alecabreralituma2@gmail.com
# services:
# - mysql
# - mongodb
# before_install:
# - mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
#Test unitario y de integracion en develop
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.organization=alexandracabreralituma-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR